<?php

declare(strict_types = 1);

/** @var \VinaiKopp\FavoriteProducts\Block\AddToFavorites $block */

?>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "vinaikopp-favorites-addto": {
                    "component": "VinaiKopp_FavoriteProducts/js/favorite-products",
                    "update_url": "<?= $block->getApiUpdateUrl() ?>"
                }
            }
        }
    }
}
</script>
<span data-bind="scope: 'vinaikopp-favorites-addto'">
    <a href="#" data-bind="
    click: select('<?= $block->escapeJs($block->getProductSku()) ?>'),
    text: isFavorite('<?= $block->escapeJs($block->getProductSku()) ?>') ?
        '<?= __('Unfavorite!') ?>' :
        '<?= __('Favorite!') ?>'"></a>
</span>
